[project]
authors = [{name = "Gabriel Talbert Bunt", email = "gabe@dendry.net"}]
dependencies = []
name = "ActiveSGM"
requires-python = "== 3.8"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tool.pixi.pypi-dependencies]
activesgm = { path = ".", editable = true }

[tool.pixi.feature.viper.system-requirements]
cuda = "12.2"

[tool.pixi.feature.viper.dependencies]
cuda-version = "12.2.*"

[tool.pixi.dependencies]
pyright = "*"
pytorch-gpu = "*"
cmake = "3.14.*"

[tool.pixi.dependencies.habitat]
git = "https://github.com/GabrielDTB/habitat-sim-hz"

[tool.pixi.environments]
viper = ["viper"]
default = ["viper"]
